name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: "0"
          fetch-tags: "true"
          submodules: "recursive"

      - name: clone core
        run:
          git clone -b my https://github.com/Asutorufa/tailscale.git

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          check-latest: true
          go-version: 'stable'
          cache-dependency-path: |
            tailscale/go.sum
            appctr/go.sum

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: build core
        run: |
          export CORE_HOME=${PWD}/tailscale
          sh app/src/main/jniLibs/build.sh

      - name: build appctr
        run: |
          cd appctr
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init
          sh build.sh

      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew app:assembleDebug --stacktrace

      - name: upload_apks
        uses: actions/upload-artifact@v5
        with:
          name: tailscaled-debug-apks
          path: app/build/outputs/apk/debug/*.apk
